In [1]:
from app import App

testApp = App(standalone=True)

testApp.run()

In [6]:
import utilities as u
import numpy as np
testArr = [1,2,3,4,5,6,7,8,9,10,11,12]
testArr2 = np.reshape(testArr,(-1,3))
print(testArr2)
testArr3 = u.combine_into_vectors(testArr)
print(testArr3)
testArr4 = np.array(testArr3)
print(testArr4.shape)
print(testArr4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[array([[1],
       [2],
       [3]]), array([[4],
       [5],
       [6]]), array([[7],
       [8],
       [9]]), array([[10],
       [11],
       [12]])]
(4, 3, 1)
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [9]:
points = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(points)
points2 = np.reshape(points,(-1))
print(type(points2))
print(points2)
points3 = list(points2)
print(type(points3))
print(points3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
<class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12]
<class 'list'>
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


In [1]:
from test_simulator2 import SimulationHandler as sim
from part_material import Material as pmaterial

testSim = sim({"Triangles": [1,2,3]},pmaterial("testMaterial",5))

       __       ___      ___   ___                _______  _______ .___  ___. 
      |  |     /   \     \  \ /  /               |   ____||   ____||   \/   | 
      |  |    /  ^  \     \  V  /      ______    |  |__   |  |__   |  \  /  | 
.--.  |  |   /  /_\  \     >   <      |______|   |   __|  |   __|  |  |\/|  | 
|  `--'  |  /  _____  \   /  .  \                |  |     |  |____ |  |  |  | 
 \______/  /__/     \__\ /__/ \__\               |__|     |_______||__|  |__| 
                                                                              

Setting material to testMaterial


In [2]:
from scipy.spatial.transform import Rotation
rot1 = Rotation.from_euler('x',50,degrees=True)
rot2 = Rotation.from_euler('y',10,degrees=True)
rc = Rotation.concatenate([rot1,rot2])
rotFin = list(rc.as_quat())
rotFin

[array([0.42262, 0.     , 0.     , 0.90631]),
 array([0.     , 0.08716, 0.     , 0.99619])]

In [3]:
hits = [1]
force = 3
quaternion = list(Rotation.from_euler('y',10,degrees=True).as_quat())
translation_vector = [0,0,0]
num_segments = 1
result = testSim.execute_simulation(hits,force,quaternion,translation_vector,num_segments)

[06-28 14:20:38][DEBUG] jax_fem: Computing shape function values, gradients, etc.
[06-28 14:20:38][DEBUG] jax_fem: ele_type = HEX8, quad_points.shape = (num_quads, dim) = (8, 3)
[06-28 14:20:38][DEBUG] jax_fem: face_quad_points.shape = (num_faces, num_face_quads, dim) = (6, 4, 3)


[06-28 14:20:38][DEBUG] jax_fem: Done pre-computations, took 0.01792168617248535 [s]
[06-28 14:20:38][INFO] jax_fem: Solving a problem with 729 cells, 1000x3 = 3000 dofs.


Info    : Meshing 1D...
Info    : [  0%] Meshing curve 1 (Extruded)
Info    : [ 10%] Meshing curve 2 (Extruded)
Info    : [ 20%] Meshing curve 3 (Extruded)
Info    : [ 30%] Meshing curve 4 (Extruded)
Info    : [ 40%] Meshing curve 7 (Extruded)
Info    : [ 50%] Meshing curve 8 (Extruded)
Info    : [ 50%] Meshing curve 9 (Extruded)
Info    : [ 60%] Meshing curve 10 (Extruded)
Info    : [ 70%] Meshing curve 12 (Extruded)
Info    : [ 80%] Meshing curve 13 (Extruded)
Info    : [ 90%] Meshing curve 17 (Extruded)
Info    : [100%] Meshing curve 21 (Extruded)
Info    : Done meshing 1D (Wall 0.00010611s, CPU 4.7e-05s)
Info    : Meshing 2D...
Info    : [  0%] Meshing surface 5 (Extruded)
Info    : [ 20%] Meshing surface 14 (Extruded)
Info    : [ 40%] Meshing surface 18 (Extruded)
Info    : [ 50%] Meshing surface 22 (Extruded)
Info    : [ 70%] Meshing surface 26 (Extruded)
Info    : [ 90%] Meshing surface 27 (Extruded)
Info    : Done meshing 2D (Wall 0.001364s, CPU 0.001424s)
Info    : Meshing 3D.

/home/timothy/GitHub/NeoForgeServer/src/Library/create_press.py:19: UserWarning: Optimal rotation is not uniquely or poorly defined for the given sets of vectors.
  rot,_ = Rotation.align_vectors([[0.,0.,-1.]],[displacement])
/home/timothy/GitHub/NeoForgeServer/src/Library/create_press.py:17: UserWarning: Optimal rotation is not uniquely or poorly defined for the given sets of vectors.
  rot,_ = Rotation.align_vectors([[0.,0.,1.]],[displacement])


STEP 1 OF 100
DirichletBCInfo: 1.1230027675628662
Simulation: 6.323411226272583
Update: 7.46991491317749
STEP 2 OF 100
DirichletBCInfo: 0.05884218215942383
Simulation: 4.093607664108276
Update: 4.154475688934326
STEP 3 OF 100
DirichletBCInfo: 0.3938930034637451
Simulation: 4.595734357833862
Update: 4.991989374160767
STEP 4 OF 100
DirichletBCInfo: 0.06142830848693848
Simulation: 4.058856725692749
Update: 4.122258186340332
STEP 5 OF 100
DirichletBCInfo: 0.2615478038787842
Simulation: 4.9095118045806885
Update: 5.173442840576172
STEP 6 OF 100
DirichletBCInfo: 0.5073626041412354
Simulation: 4.965070962905884
Update: 5.474911689758301
STEP 7 OF 100
DirichletBCInfo: 0.37648940086364746
Simulation: 4.118391990661621
Update: 4.496201992034912
STEP 8 OF 100
DirichletBCInfo: 0.05323338508605957
Simulation: 3.760702133178711
Update: 3.816014051437378
STEP 9 OF 100
DirichletBCInfo: 0.5010650157928467
Simulation: 5.0746378898620605
Update: 5.578113794326782
STEP 10 OF 100
DirichletBCInfo: 0.2047080

In [6]:
testList = [1,2,3]
[-x for x in testList[:2]]

[-1, -2]

In [1]:
from vtk_plotting import create_gif
data_dir = 'data/runs/run_005'
create_gif(data_dir,data_dir)
create_gif(data_dir,data_dir,name="animation2.gif",negative=True)

In [ ]:
import tetgen
import pyvista as pv
import meshio
def convert_stl_to_tetrahedral(stl_path, output_path):
mesh = pv.read(stl_path)
tet = tetgen.TetGen(mesh)
tet.tetrahedralize(order=1, mindihedral=20, minratio=1.5)
tet_mesh = tet.grid
tet_mesh.save(output_path)
print(f"Tetrahedral mesh saved to {output_path}")
convert_stl_to_tetrahedral("./cylinder_low.stl", "output_cyl_low.vtk")
mesh = meshio.read("output_cyl_low.vtk")
print(mesh)