In [1]:
from app import App

testApp = App(standalone=True)

testApp.run()

In [6]:
import utilities as u
import numpy as np
testArr = [1,2,3,4,5,6,7,8,9,10,11,12]
testArr2 = np.reshape(testArr,(-1,3))
print(testArr2)
testArr3 = u.combine_into_vectors(testArr)
print(testArr3)
testArr4 = np.array(testArr3)
print(testArr4.shape)
print(testArr4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[array([[1],
       [2],
       [3]]), array([[4],
       [5],
       [6]]), array([[7],
       [8],
       [9]]), array([[10],
       [11],
       [12]])]
(4, 3, 1)
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [9]:
points = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(points)
points2 = np.reshape(points,(-1))
print(type(points2))
print(points2)
points3 = list(points2)
print(type(points3))
print(points3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
<class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12]
<class 'list'>
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


In [1]:
from test_simulator2 import SimulationHandler as sim
from part_material import Material as pmaterial

testSim = sim({"Triangles": [1,2,3]},pmaterial("testMaterial",5))

       __       ___      ___   ___                _______  _______ .___  ___. 
      |  |     /   \     \  \ /  /               |   ____||   ____||   \/   | 
      |  |    /  ^  \     \  V  /      ______    |  |__   |  |__   |  \  /  | 
.--.  |  |   /  /_\  \     >   <      |______|   |   __|  |   __|  |  |\/|  | 
|  `--'  |  /  _____  \   /  .  \                |  |     |  |____ |  |  |  | 
 \______/  /__/     \__\ /__/ \__\               |__|     |_______||__|  |__| 
                                                                              

Setting material to testMaterial


In [2]:
from scipy.spatial.transform import Rotation
rot1 = Rotation.from_euler('x',50,degrees=True)
rot2 = Rotation.from_euler('y',10,degrees=True)
rc = Rotation.concatenate([rot1,rot2])
rotFin = list(rc.as_quat())
rotFin

[array([0.42262, 0.     , 0.     , 0.90631]),
 array([0.     , 0.08716, 0.     , 0.99619])]

In [3]:
hits = [1]
force = 3
quaternion = list(Rotation.from_euler('y',10,degrees=True).as_quat())
translation_vector = [0,0,0]
num_segments = 1
result = testSim.execute_simulation(hits,force,quaternion,translation_vector,num_segments)

[06-27 00:19:00][DEBUG] jax_fem: Computing shape function values, gradients, etc.
[06-27 00:19:00][DEBUG] jax_fem: ele_type = HEX8, quad_points.shape = (num_quads, dim) = (8, 3)
[06-27 00:19:00][DEBUG] jax_fem: face_quad_points.shape = (num_faces, num_face_quads, dim) = (6, 4, 3)


[06-27 00:19:00][DEBUG] jax_fem: Done pre-computations, took 0.018847227096557617 [s]
[06-27 00:19:00][INFO] jax_fem: Solving a problem with 729 cells, 1000x3 = 3000 dofs.


Info    : Meshing 1D...
Info    : [  0%] Meshing curve 1 (Extruded)
Info    : [ 10%] Meshing curve 2 (Extruded)
Info    : [ 20%] Meshing curve 3 (Extruded)
Info    : [ 30%] Meshing curve 4 (Extruded)
Info    : [ 40%] Meshing curve 7 (Extruded)
Info    : [ 50%] Meshing curve 8 (Extruded)
Info    : [ 50%] Meshing curve 9 (Extruded)
Info    : [ 60%] Meshing curve 10 (Extruded)
Info    : [ 70%] Meshing curve 12 (Extruded)
Info    : [ 80%] Meshing curve 13 (Extruded)
Info    : [ 90%] Meshing curve 17 (Extruded)
Info    : [100%] Meshing curve 21 (Extruded)
Info    : Done meshing 1D (Wall 6.0765e-05s, CPU 3e-05s)
Info    : Meshing 2D...
Info    : [  0%] Meshing surface 5 (Extruded)
Info    : [ 20%] Meshing surface 14 (Extruded)
Info    : [ 40%] Meshing surface 18 (Extruded)
Info    : [ 50%] Meshing surface 22 (Extruded)
Info    : [ 70%] Meshing surface 26 (Extruded)
Info    : [ 90%] Meshing surface 27 (Extruded)
Info    : Done meshing 2D (Wall 0.00143899s, CPU 0.000955s)
Info    : Meshing 3D.

/home/timothy/GitHub/NeoForgeServer/src/Library/create_press.py:19: UserWarning: Optimal rotation is not uniquely or poorly defined for the given sets of vectors.
  rot,_ = Rotation.align_vectors([[0.,0.,-1.]],[displacement])
/home/timothy/GitHub/NeoForgeServer/src/Library/create_press.py:17: UserWarning: Optimal rotation is not uniquely or poorly defined for the given sets of vectors.
  rot,_ = Rotation.align_vectors([[0.,0.,1.]],[displacement])


STEP 1 OF 100
COMBINED_CHECKS
(1000,)
1
COMBINED_DISPLACEMENTS
(1000, 3)
[[0. 0. 0.]]
TABLE
COMBINED_CHECKS
(1000,)
1
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.  0. -0.]]
DirichletBCInfo: 1.0810673236846924


[06-27 00:19:03][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:19:03][DEBUG] jax_fem: Start timing
[06-27 00:19:04][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:19:04][DEBUG] jax_fem: Function split_and_compute_cell took 0.7015 seconds
[06-27 00:19:05][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:06][DEBUG] jax_fem: Before, res l_2 = 0.0050175222445636445
[06-27 00:19:06][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:19:06][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:19:07][DEBUG] jax_fem: JAX scipy linear solve res = 7.305570051860553e-06
[06-27 00:19:07][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:19:07][DEBUG] jax_fem: Function split_and_compute_cell took 0.0850 seconds
[06-27 00:19:07][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:07][DEBUG] jax_fem: res l_2 = 7.3055700518595604e-06
[06-27 00:19:07][INFO] 

Simulation: 5.340022087097168
STEP 2 OF 100
COMBINED_CHECKS
(1000,)
1
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.    0.   -0.03]]
TABLE
COMBINED_CHECKS
(1000,)
1
COMBINED_DISPLACEMENTS
(1000, 3)
[[0. 0. 0.]]
DirichletBCInfo: 0.07463908195495605


[06-27 00:19:08][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:19:08][DEBUG] jax_fem: Start timing
[06-27 00:19:08][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:19:08][DEBUG] jax_fem: Function split_and_compute_cell took 0.0820 seconds
[06-27 00:19:08][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:08][DEBUG] jax_fem: Before, res l_2 = 249.14587784333548
[06-27 00:19:08][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:19:08][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:19:09][DEBUG] jax_fem: JAX scipy linear solve res = 0.0024677503910080973
[06-27 00:19:09][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:19:09][DEBUG] jax_fem: Function split_and_compute_cell took 0.0623 seconds
[06-27 00:19:09][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:09][DEBUG] jax_fem: res l_2 = 25.764382016426453
[06-27 00:19:09][DEBUG] jax_fe

Simulation: 4.724116325378418
STEP 3 OF 100
COMBINED_CHECKS
(1000,)
1
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.    0.   -0.03]]
TABLE
COMBINED_CHECKS
(1000,)
1
COMBINED_DISPLACEMENTS
(1000, 3)
[[0. 0. 0.]]
DirichletBCInfo: 0.0621950626373291


[06-27 00:19:12][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:19:12][DEBUG] jax_fem: Start timing
[06-27 00:19:12][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:19:12][DEBUG] jax_fem: Function split_and_compute_cell took 0.0802 seconds
[06-27 00:19:12][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:12][DEBUG] jax_fem: Before, res l_2 = 251.57142883675178
[06-27 00:19:12][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:19:12][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:19:13][DEBUG] jax_fem: JAX scipy linear solve res = 0.0020717349758256997
[06-27 00:19:13][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:19:13][DEBUG] jax_fem: Function split_and_compute_cell took 0.0689 seconds
[06-27 00:19:13][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:13][DEBUG] jax_fem: res l_2 = 8.235804626115362
[06-27 00:19:13][DEBUG] jax_fem

Simulation: 3.6647744178771973
STEP 4 OF 100
COMBINED_CHECKS
(1000,)
2
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.       0.      -0.03   ]
 [ 0.       0.      -0.00079]]
TABLE
COMBINED_CHECKS
(1000,)
2
COMBINED_DISPLACEMENTS
(1000, 3)
[[0.    0.    0.   ]
 [0.    0.    0.014]]
DirichletBCInfo: 0.38648295402526855


[06-27 00:19:17][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:19:17][DEBUG] jax_fem: Start timing
[06-27 00:19:17][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:19:17][DEBUG] jax_fem: Function split_and_compute_cell took 0.0835 seconds
[06-27 00:19:17][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:17][DEBUG] jax_fem: Before, res l_2 = 269.467578188311
[06-27 00:19:17][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:19:17][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:19:18][DEBUG] jax_fem: JAX scipy linear solve res = 0.0026528455292193294
[06-27 00:19:18][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:19:18][DEBUG] jax_fem: Function split_and_compute_cell took 0.0626 seconds
[06-27 00:19:18][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:18][DEBUG] jax_fem: res l_2 = 22.215455724071898
[06-27 00:19:18][DEBUG] jax_fem:

Simulation: 4.833705425262451
STEP 5 OF 100
COMBINED_CHECKS
(1000,)
2
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.    0.   -0.03]
 [ 0.    0.   -0.03]]
TABLE
COMBINED_CHECKS
(1000,)
2
COMBINED_DISPLACEMENTS
(1000, 3)
[[0. 0. 0.]
 [0. 0. 0.]]
DirichletBCInfo: 0.053644418716430664


[06-27 00:19:21][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:19:21][DEBUG] jax_fem: Start timing
[06-27 00:19:21][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:19:21][DEBUG] jax_fem: Function split_and_compute_cell took 0.0583 seconds
[06-27 00:19:21][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:21][DEBUG] jax_fem: Before, res l_2 = 403.8106062781956
[06-27 00:19:21][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:19:21][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:19:22][DEBUG] jax_fem: JAX scipy linear solve res = 0.0008641692831012587
[06-27 00:19:22][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:19:22][DEBUG] jax_fem: Function split_and_compute_cell took 0.0752 seconds
[06-27 00:19:22][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:22][DEBUG] jax_fem: res l_2 = 8.277016517078625
[06-27 00:19:22][DEBUG] jax_fem:

Simulation: 3.1658670902252197
STEP 6 OF 100
COMBINED_CHECKS
(1000,)
2
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.    0.   -0.03]
 [ 0.    0.   -0.03]]
TABLE
COMBINED_CHECKS
(1000,)
3
COMBINED_DISPLACEMENTS
(1000, 3)
[[0.     0.     0.    ]
 [0.     0.     0.    ]
 [0.     0.     0.0018]]
DirichletBCInfo: 0.2620720863342285


[06-27 00:19:25][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:19:25][DEBUG] jax_fem: Start timing
[06-27 00:19:25][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:19:25][DEBUG] jax_fem: Function split_and_compute_cell took 0.0661 seconds
[06-27 00:19:26][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:26][DEBUG] jax_fem: Before, res l_2 = 404.3225956507832
[06-27 00:19:26][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:19:26][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:19:26][DEBUG] jax_fem: JAX scipy linear solve res = 0.003755997708060226
[06-27 00:19:26][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:19:26][DEBUG] jax_fem: Function split_and_compute_cell took 0.0866 seconds
[06-27 00:19:27][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:27][DEBUG] jax_fem: res l_2 = 12.90659782830865
[06-27 00:19:27][DEBUG] jax_fem: 

Simulation: 4.004020929336548
STEP 7 OF 100
COMBINED_CHECKS
(1000,)
3
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.01786]]
TABLE
COMBINED_CHECKS
(1000,)
3
COMBINED_DISPLACEMENTS
(1000, 3)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
DirichletBCInfo: 0.1475355625152588


[06-27 00:19:29][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:19:29][DEBUG] jax_fem: Start timing
[06-27 00:19:29][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:19:29][DEBUG] jax_fem: Function split_and_compute_cell took 0.0803 seconds
[06-27 00:19:29][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:29][DEBUG] jax_fem: Before, res l_2 = 454.0076713544793
[06-27 00:19:29][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:19:29][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:19:30][DEBUG] jax_fem: JAX scipy linear solve res = 0.0043785982417557465
[06-27 00:19:30][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:19:30][DEBUG] jax_fem: Function split_and_compute_cell took 0.0795 seconds
[06-27 00:19:30][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:30][DEBUG] jax_fem: res l_2 = 6.804590981281036
[06-27 00:19:30][DEBUG] jax_fem:

Simulation: 3.3703432083129883
STEP 8 OF 100
COMBINED_CHECKS
(1000,)
4
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.00014]]
TABLE
COMBINED_CHECKS
(1000,)
4
COMBINED_DISPLACEMENTS
(1000, 3)
[[0.      0.      0.     ]
 [0.      0.      0.     ]
 [0.      0.      0.     ]
 [0.      0.      0.00388]]
DirichletBCInfo: 0.35599565505981445


[06-27 00:19:33][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:19:33][DEBUG] jax_fem: Start timing
[06-27 00:19:33][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:19:33][DEBUG] jax_fem: Function split_and_compute_cell took 0.0845 seconds
[06-27 00:19:33][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:34][DEBUG] jax_fem: Before, res l_2 = 509.461444709696
[06-27 00:19:34][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:19:34][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:19:34][DEBUG] jax_fem: JAX scipy linear solve res = 0.002933409187905018
[06-27 00:19:34][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:19:34][DEBUG] jax_fem: Function split_and_compute_cell took 0.0767 seconds
[06-27 00:19:34][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:34][DEBUG] jax_fem: res l_2 = 16.928149681151492
[06-27 00:19:34][DEBUG] jax_fem: 

Simulation: 4.210385322570801
STEP 9 OF 100
COMBINED_CHECKS
(1000,)
4
COMBINED_DISPLACEMENTS
(1000, 3)


[06-27 00:19:37][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:19:37][DEBUG] jax_fem: Start timing
[06-27 00:19:37][DEBUG] jax_fem: Computing cell Jacobian and cell residual...


[[ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]]
TABLE
COMBINED_CHECKS
(1000,)
4
COMBINED_DISPLACEMENTS
(1000, 3)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
DirichletBCInfo: 0.21424078941345215


[06-27 00:19:37][DEBUG] jax_fem: Function split_and_compute_cell took 0.0847 seconds
[06-27 00:19:37][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:37][DEBUG] jax_fem: Before, res l_2 = 602.3896940968393
[06-27 00:19:37][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:19:37][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:19:38][DEBUG] jax_fem: JAX scipy linear solve res = 0.00596452601517624
[06-27 00:19:38][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:19:38][DEBUG] jax_fem: Function split_and_compute_cell took 0.0724 seconds
[06-27 00:19:38][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:38][DEBUG] jax_fem: res l_2 = 12.813618077749803
[06-27 00:19:38][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:19:38][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:19:38][DEBUG] jax_fem: JAX scipy linear solve res = 6.235470346099302e-05
[06-27 00:19:38][DEBUG]

Simulation: 3.180208206176758
STEP 10 OF 100
COMBINED_CHECKS
(1000,)
4
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]]
TABLE
COMBINED_CHECKS
(1000,)
5
COMBINED_DISPLACEMENTS
(1000, 3)
[[0.      0.      0.     ]
 [0.      0.      0.     ]
 [0.      0.      0.     ]
 [0.      0.      0.     ]
 [0.      0.      0.02335]]
DirichletBCInfo: 0.17548608779907227


[06-27 00:19:41][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:19:41][DEBUG] jax_fem: Start timing
[06-27 00:19:41][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:19:41][DEBUG] jax_fem: Function split_and_compute_cell took 0.0864 seconds
[06-27 00:19:41][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:41][DEBUG] jax_fem: Before, res l_2 = 632.4574841206605
[06-27 00:19:41][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:19:41][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:19:42][DEBUG] jax_fem: JAX scipy linear solve res = 0.0019513005430328392
[06-27 00:19:42][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:19:42][DEBUG] jax_fem: Function split_and_compute_cell took 0.0665 seconds
[06-27 00:19:42][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:42][DEBUG] jax_fem: res l_2 = 26.268479226284292
[06-27 00:19:42][DEBUG] jax_fem

Simulation: 4.73683762550354
STEP 11 OF 100
COMBINED_CHECKS
(1000,)
4
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]]
TABLE
COMBINED_CHECKS
(1000,)
6
COMBINED_DISPLACEMENTS
(1000, 3)
[[0.      0.      0.     ]
 [0.      0.      0.     ]
 [0.      0.      0.     ]
 [0.      0.      0.     ]
 [0.      0.      0.     ]
 [0.      0.      0.01377]]
DirichletBCInfo: 0.33243656158447266


[06-27 00:19:46][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:19:46][DEBUG] jax_fem: Start timing
[06-27 00:19:46][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:19:46][DEBUG] jax_fem: Function split_and_compute_cell took 0.0905 seconds
[06-27 00:19:46][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:46][DEBUG] jax_fem: Before, res l_2 = 613.4786055598275
[06-27 00:19:46][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:19:46][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:19:47][DEBUG] jax_fem: JAX scipy linear solve res = 0.0032541689267691484
[06-27 00:19:47][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:19:47][DEBUG] jax_fem: Function split_and_compute_cell took 0.0791 seconds
[06-27 00:19:47][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:47][DEBUG] jax_fem: res l_2 = 14.391874160778224
[06-27 00:19:47][DEBUG] jax_fem

Simulation: 4.241141080856323
STEP 12 OF 100
COMBINED_CHECKS
(1000,)
4
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]]


[06-27 00:19:50][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:19:50][DEBUG] jax_fem: Start timing
[06-27 00:19:50][DEBUG] jax_fem: Computing cell Jacobian and cell residual...


TABLE
COMBINED_CHECKS
(1000,)
6
COMBINED_DISPLACEMENTS
(1000, 3)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
DirichletBCInfo: 0.2093207836151123


[06-27 00:19:50][DEBUG] jax_fem: Function split_and_compute_cell took 0.0628 seconds
[06-27 00:19:50][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:50][DEBUG] jax_fem: Before, res l_2 = 603.0400943816046
[06-27 00:19:50][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:19:50][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:19:51][DEBUG] jax_fem: JAX scipy linear solve res = 0.005813597602686855
[06-27 00:19:51][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:19:51][DEBUG] jax_fem: Function split_and_compute_cell took 0.0772 seconds
[06-27 00:19:51][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:51][DEBUG] jax_fem: res l_2 = 6.240225186931428
[06-27 00:19:51][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:19:51][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:19:52][DEBUG] jax_fem: JAX scipy linear solve res = 6.023739596078972e-05
[06-27 00:19:52][DEBUG]

Simulation: 3.6423850059509277
STEP 13 OF 100
COMBINED_CHECKS
(1000,)
4
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]]
TABLE
COMBINED_CHECKS
(1000,)
7
COMBINED_DISPLACEMENTS
(1000, 3)
[[0.      0.      0.     ]
 [0.      0.      0.     ]
 [0.      0.      0.     ]
 [0.      0.      0.     ]
 [0.      0.      0.     ]
 [0.      0.      0.     ]
 [0.      0.      0.01022]]
DirichletBCInfo: 0.18740010261535645


[06-27 00:19:54][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:19:54][DEBUG] jax_fem: Start timing
[06-27 00:19:54][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:19:54][DEBUG] jax_fem: Function split_and_compute_cell took 0.0890 seconds
[06-27 00:19:55][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:55][DEBUG] jax_fem: Before, res l_2 = 608.7811799114183
[06-27 00:19:55][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:19:55][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:19:55][DEBUG] jax_fem: JAX scipy linear solve res = 0.001997202240673743
[06-27 00:19:55][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:19:55][DEBUG] jax_fem: Function split_and_compute_cell took 0.0642 seconds
[06-27 00:19:56][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:56][DEBUG] jax_fem: res l_2 = 9.223135321179345
[06-27 00:19:56][DEBUG] jax_fem: 

Simulation: 3.992807626724243
STEP 14 OF 100
COMBINED_CHECKS
(1000,)
5
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.01013]]
TABLE
COMBINED_CHECKS
(1000,)
7
COMBINED_DISPLACEMENTS
(1000, 3)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
DirichletBCInfo: 0.1233210563659668


[06-27 00:19:58][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:19:58][DEBUG] jax_fem: Start timing
[06-27 00:19:58][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:19:58][DEBUG] jax_fem: Function split_and_compute_cell took 0.0735 seconds
[06-27 00:19:58][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:58][DEBUG] jax_fem: Before, res l_2 = 597.2259255395329
[06-27 00:19:58][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:19:58][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:19:59][DEBUG] jax_fem: JAX scipy linear solve res = 0.005824453466145032
[06-27 00:19:59][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:19:59][DEBUG] jax_fem: Function split_and_compute_cell took 0.0755 seconds
[06-27 00:19:59][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:19:59][DEBUG] jax_fem: res l_2 = 4.85246057859115
[06-27 00:19:59][DEBUG] jax_fem: S

Simulation: 3.4504482746124268
STEP 15 OF 100
COMBINED_CHECKS
(1000,)
6
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.      0.     -0.03  ]
 [ 0.      0.     -0.03  ]
 [ 0.      0.     -0.03  ]
 [ 0.      0.     -0.03  ]
 [ 0.      0.     -0.0015]
 [ 0.      0.     -0.03  ]]
TABLE
COMBINED_CHECKS
(1000,)
7
COMBINED_DISPLACEMENTS
(1000, 3)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
DirichletBCInfo: 0.11760854721069336


[06-27 00:20:01][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:20:01][DEBUG] jax_fem: Start timing
[06-27 00:20:01][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:20:01][DEBUG] jax_fem: Function split_and_compute_cell took 0.0805 seconds
[06-27 00:20:02][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:20:02][DEBUG] jax_fem: Before, res l_2 = 660.5496919200503
[06-27 00:20:02][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:20:02][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:20:02][DEBUG] jax_fem: JAX scipy linear solve res = 0.004133884007067556
[06-27 00:20:02][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:20:02][DEBUG] jax_fem: Function split_and_compute_cell took 0.0692 seconds
[06-27 00:20:03][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:20:03][DEBUG] jax_fem: res l_2 = 6.388129933122583
[06-27 00:20:03][DEBUG] jax_fem: 

Simulation: 3.33451509475708
STEP 16 OF 100
COMBINED_CHECKS
(1000,)
7
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.00337]
 [ 0.       0.      -0.03   ]]
TABLE
COMBINED_CHECKS
(1000,)
8
COMBINED_DISPLACEMENTS
(1000, 3)
[[0.      0.      0.     ]
 [0.      0.      0.     ]
 [0.      0.      0.     ]
 [0.      0.      0.     ]
 [0.      0.      0.     ]
 [0.      0.      0.     ]
 [0.      0.      0.     ]
 [0.      0.      0.00917]]
DirichletBCInfo: 0.3814854621887207


[06-27 00:20:06][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:20:06][DEBUG] jax_fem: Start timing
[06-27 00:20:06][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:20:06][DEBUG] jax_fem: Function split_and_compute_cell took 0.0902 seconds
[06-27 00:20:06][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:20:06][DEBUG] jax_fem: Before, res l_2 = 688.2700301582591
[06-27 00:20:06][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:20:06][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:20:07][DEBUG] jax_fem: JAX scipy linear solve res = 0.005397357944776031
[06-27 00:20:07][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:20:07][DEBUG] jax_fem: Function split_and_compute_cell took 0.0809 seconds
[06-27 00:20:07][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:20:07][DEBUG] jax_fem: res l_2 = 11.595608680085107
[06-27 00:20:07][DEBUG] jax_fem:

Simulation: 5.56969428062439
STEP 17 OF 100
COMBINED_CHECKS
(1000,)
9
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.00263]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.01518]]
TABLE
COMBINED_CHECKS
(1000,)
8
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0. -0.]]
DirichletBCInfo: 0.380054235458374


[06-27 00:20:12][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:20:12][DEBUG] jax_fem: Start timing
[06-27 00:20:12][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:20:12][DEBUG] jax_fem: Function split_and_compute_cell took 0.0760 seconds
[06-27 00:20:12][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:20:12][DEBUG] jax_fem: Before, res l_2 = 752.235523092634
[06-27 00:20:12][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:20:12][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:20:13][DEBUG] jax_fem: JAX scipy linear solve res = 0.00504471179914616
[06-27 00:20:13][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:20:13][DEBUG] jax_fem: Function split_and_compute_cell took 0.0844 seconds
[06-27 00:20:13][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:20:13][DEBUG] jax_fem: res l_2 = 7.55585224102927
[06-27 00:20:13][DEBUG] jax_fem: Sol

Simulation: 4.294089317321777
STEP 18 OF 100
COMBINED_CHECKS
(1000,)
10
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.00772]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]]
TABLE
COMBINED_CHECKS
(1000,)
8
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0. -0.]]
DirichletBCInfo: 0.36023545265197754


[06-27 00:20:17][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:20:17][DEBUG] jax_fem: Start timing
[06-27 00:20:17][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:20:17][DEBUG] jax_fem: Function split_and_compute_cell took 0.0860 seconds
[06-27 00:20:17][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:20:17][DEBUG] jax_fem: Before, res l_2 = 852.89316514577
[06-27 00:20:17][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:20:17][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:20:18][DEBUG] jax_fem: JAX scipy linear solve res = 0.002842098195477874
[06-27 00:20:18][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:20:18][DEBUG] jax_fem: Function split_and_compute_cell took 0.0780 seconds
[06-27 00:20:18][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:20:18][DEBUG] jax_fem: res l_2 = 7.339578932126313
[06-27 00:20:18][DEBUG] jax_fem: So

Simulation: 4.617641448974609
STEP 19 OF 100
COMBINED_CHECKS
(1000,)
10
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]]
TABLE
COMBINED_CHECKS
(1000,)
9
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.      -0.     ]
 [ 0.       0.       0.01735]]
DirichletBCInfo: 0.10703372955322266


[06-27 00:20:20][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:20:20][DEBUG] jax_fem: Start timing
[06-27 00:20:20][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:20:21][DEBUG] jax_fem: Function split_and_compute_cell took 0.0752 seconds
[06-27 00:20:21][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:20:21][DEBUG] jax_fem: Before, res l_2 = 937.4511928463165
[06-27 00:20:21][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:20:21][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:20:21][DEBUG] jax_fem: JAX scipy linear solve res = 0.003300844533530822
[06-27 00:20:21][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:20:21][DEBUG] jax_fem: Function split_and_compute_cell took 0.0761 seconds
[06-27 00:20:22][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:20:22][DEBUG] jax_fem: res l_2 = 11.115255503267472
[06-27 00:20:22][DEBUG] jax_fem:

Simulation: 5.194695949554443
STEP 20 OF 100
COMBINED_CHECKS
(1000,)
11
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.01022]]
TABLE
COMBINED_CHECKS
(1000,)
9
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0. -0.]
 [ 0.  0.  0.]]
DirichletBCInfo: 0.3996257781982422


[06-27 00:20:27][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:20:27][DEBUG] jax_fem: Start timing
[06-27 00:20:27][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:20:27][DEBUG] jax_fem: Function split_and_compute_cell took 0.0899 seconds
[06-27 00:20:27][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:20:27][DEBUG] jax_fem: Before, res l_2 = 899.3213653064448
[06-27 00:20:27][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:20:27][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:20:28][DEBUG] jax_fem: JAX scipy linear solve res = 0.00034608334247183536
[06-27 00:20:28][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:20:28][DEBUG] jax_fem: Function split_and_compute_cell took 0.0847 seconds
[06-27 00:20:28][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:20:28][DEBUG] jax_fem: res l_2 = 4.964118969310111
[06-27 00:20:28][DEBUG] jax_fem

Simulation: 4.921695709228516
STEP 21 OF 100
COMBINED_CHECKS
(1000,)
11
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]]
TABLE
COMBINED_CHECKS
(1000,)
10
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.       0.       0.     ]
 [ 0.       0.       0.00975]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.      -0.     ]
 [ 0.       0.      -0.     ]]
DirichletBCInfo: 0.11055374145507812


[06-27 00:20:31][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:20:31][DEBUG] jax_fem: Start timing
[06-27 00:20:31][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:20:31][DEBUG] jax_fem: Function split_and_compute_cell took 0.0629 seconds
[06-27 00:20:31][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:20:31][DEBUG] jax_fem: Before, res l_2 = 916.8027926231663
[06-27 00:20:31][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:20:31][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:20:32][DEBUG] jax_fem: JAX scipy linear solve res = 0.009156384924972755
[06-27 00:20:32][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:20:32][DEBUG] jax_fem: Function split_and_compute_cell took 0.0724 seconds
[06-27 00:20:32][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:20:32][DEBUG] jax_fem: res l_2 = 5.28038951532639
[06-27 00:20:32][DEBUG] jax_fem: S

Simulation: 3.755774736404419
STEP 22 OF 100
COMBINED_CHECKS
(1000,)
11
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]]
TABLE
COMBINED_CHECKS
(1000,)
11
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.      0.      0.    ]
 [ 0.      0.     -0.    ]
 [ 0.      0.      0.    ]
 [ 0.      0.      0.    ]
 [ 0.      0.      0.    ]
 [ 0.      0.      0.    ]
 [ 0.      0.      0.    ]
 [ 0.      0.      0.    ]
 [ 0.      0.     -0.    ]
 [ 0.      0.     -0.    ]
 [ 0.      0.      0.0043]]
DirichletBCInfo: 0.1019437313079834


[06-27 00:20:35][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:20:35][DEBUG] jax_fem: Start timing
[06-27 00:20:35][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:20:35][DEBUG] jax_fem: Function split_and_compute_cell took 0.0820 seconds
[06-27 00:20:35][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:20:35][DEBUG] jax_fem: Before, res l_2 = 916.2696827519205
[06-27 00:20:35][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:20:35][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:20:36][DEBUG] jax_fem: JAX scipy linear solve res = 0.003974195437376715
[06-27 00:20:36][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:20:36][DEBUG] jax_fem: Function split_and_compute_cell took 0.0736 seconds
[06-27 00:20:36][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:20:36][DEBUG] jax_fem: res l_2 = 4.49045972663783
[06-27 00:20:36][DEBUG] jax_fem: S

Simulation: 3.8660624027252197
STEP 23 OF 100
COMBINED_CHECKS
(1000,)
12
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.00519]
 [ 0.       0.      -0.03   ]]
TABLE
COMBINED_CHECKS
(1000,)
11
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.  0.  0.]
 [ 0.  0. -0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0. -0.]
 [ 0.  0. -0.]
 [ 0.  0.  0.]]
DirichletBCInfo: 0.25255441665649414


[06-27 00:20:40][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:20:40][DEBUG] jax_fem: Start timing
[06-27 00:20:40][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:20:40][DEBUG] jax_fem: Function split_and_compute_cell took 0.0921 seconds
[06-27 00:20:40][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:20:40][DEBUG] jax_fem: Before, res l_2 = 888.9158659360463
[06-27 00:20:40][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:20:40][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:20:41][DEBUG] jax_fem: JAX scipy linear solve res = 0.008747134736230304
[06-27 00:20:41][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:20:41][DEBUG] jax_fem: Function split_and_compute_cell took 0.0782 seconds
[06-27 00:20:41][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:20:41][DEBUG] jax_fem: res l_2 = 3.650050478225639
[06-27 00:20:41][DEBUG] jax_fem: 

Simulation: 4.568528175354004
STEP 24 OF 100
COMBINED_CHECKS
(1000,)
12
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]]
TABLE
COMBINED_CHECKS
(1000,)
13
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.       0.       0.     ]
 [ 0.       0.      -0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.      -0.     ]
 [ 0.       0.      -0.     ]
 [ 0.       0.       0.00256]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.00363]]
DirichletBCInfo: 0.19262933731079102


[06-27 00:20:45][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:20:45][DEBUG] jax_fem: Start timing
[06-27 00:20:45][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:20:45][DEBUG] jax_fem: Function split_and_compute_cell took 0.0929 seconds
[06-27 00:20:45][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:20:45][DEBUG] jax_fem: Before, res l_2 = 923.643693528098
[06-27 00:20:45][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:20:45][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:20:46][DEBUG] jax_fem: JAX scipy linear solve res = 0.006831110392639872
[06-27 00:20:46][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:20:46][DEBUG] jax_fem: Function split_and_compute_cell took 0.0664 seconds
[06-27 00:20:46][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:20:46][DEBUG] jax_fem: res l_2 = 4.812747286459803
[06-27 00:20:46][DEBUG] jax_fem: S

Simulation: 4.658179521560669
STEP 25 OF 100
COMBINED_CHECKS
(1000,)
14
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.00168]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.00593]]
TABLE
COMBINED_CHECKS
(1000,)
13
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.  0.  0.]
 [ 0.  0. -0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0. -0.]
 [ 0.  0. -0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
DirichletBCInfo: 0.3084743022918701


[06-27 00:20:50][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:20:50][DEBUG] jax_fem: Start timing
[06-27 00:20:50][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:20:50][DEBUG] jax_fem: Function split_and_compute_cell took 0.0847 seconds
[06-27 00:20:50][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:20:50][DEBUG] jax_fem: Before, res l_2 = 856.0880439672233
[06-27 00:20:50][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:20:50][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:20:51][DEBUG] jax_fem: JAX scipy linear solve res = 0.005846861700172879
[06-27 00:20:51][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:20:51][DEBUG] jax_fem: Function split_and_compute_cell took 0.0654 seconds
[06-27 00:20:51][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:20:51][DEBUG] jax_fem: res l_2 = 3.952952525185774
[06-27 00:20:51][DEBUG] jax_fem: 

Simulation: 4.764497756958008
STEP 26 OF 100


[06-27 00:20:54][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:20:54][DEBUG] jax_fem: Start timing
[06-27 00:20:54][DEBUG] jax_fem: Computing cell Jacobian and cell residual...


COMBINED_CHECKS
(1000,)
14
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]]
TABLE
COMBINED_CHECKS
(1000,)
13
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.  0.  0.]
 [ 0.  0. -0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0. -0.]
 [ 0.  0. -0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
DirichletBCInfo: 0.22875118255615234


[06-27 00:20:54][DEBUG] jax_fem: Function split_and_compute_cell took 0.0942 seconds
[06-27 00:20:54][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:20:54][DEBUG] jax_fem: Before, res l_2 = 925.4449236217218
[06-27 00:20:54][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:20:54][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:20:55][DEBUG] jax_fem: JAX scipy linear solve res = 0.008567595318919735
[06-27 00:20:55][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:20:55][DEBUG] jax_fem: Function split_and_compute_cell took 0.0850 seconds
[06-27 00:20:55][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:20:55][DEBUG] jax_fem: res l_2 = 3.0187679966025667
[06-27 00:20:55][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:20:55][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:20:56][DEBUG] jax_fem: JAX scipy linear solve res = 2.449661748577113e-05
[06-27 00:20:56][DEBUG

Simulation: 3.121774911880493
STEP 27 OF 100
COMBINED_CHECKS
(1000,)
15
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.00548]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]]
TABLE
COMBINED_CHECKS
(1000,)
14
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.       0.       0.     ]
 [ 0.       0.      -0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.      -0.     ]
 [ 0.       0.      -0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.    

[06-27 00:20:58][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:20:58][DEBUG] jax_fem: Start timing
[06-27 00:20:58][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:20:58][DEBUG] jax_fem: Function split_and_compute_cell took 0.0796 seconds
[06-27 00:20:58][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:20:58][DEBUG] jax_fem: Before, res l_2 = 908.0279122151732
[06-27 00:20:58][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:20:58][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:20:59][DEBUG] jax_fem: JAX scipy linear solve res = 0.007894830689574205
[06-27 00:20:59][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:20:59][DEBUG] jax_fem: Function split_and_compute_cell took 0.0691 seconds
[06-27 00:20:59][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:20:59][DEBUG] jax_fem: res l_2 = 3.1767681605760094
[06-27 00:20:59][DEBUG] jax_fem:

Simulation: 4.011520147323608
STEP 28 OF 100
COMBINED_CHECKS
(1000,)
16
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.00687]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]]
TABLE
COMBINED_CHECKS
(1000,)
15
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.       0.       0.     ]
 [ 0.       0.      -0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.      -0.     ]
 [ 0.       0.      -0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.    

[06-27 00:21:02][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:21:02][DEBUG] jax_fem: Start timing
[06-27 00:21:02][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:21:02][DEBUG] jax_fem: Function split_and_compute_cell took 0.0807 seconds
[06-27 00:21:03][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:21:03][DEBUG] jax_fem: Before, res l_2 = 936.683187014555
[06-27 00:21:03][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:21:03][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:21:04][DEBUG] jax_fem: JAX scipy linear solve res = 0.005115801887653408
[06-27 00:21:04][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:21:04][DEBUG] jax_fem: Function split_and_compute_cell took 0.0877 seconds
[06-27 00:21:04][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:21:04][DEBUG] jax_fem: res l_2 = 3.4152762594609083
[06-27 00:21:04][DEBUG] jax_fem: 

Simulation: 3.9456827640533447
STEP 29 OF 100
COMBINED_CHECKS
(1000,)
16
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]]
TABLE
COMBINED_CHECKS
(1000,)
16
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.       0.       0.     ]
 [ 0.       0.      -0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.      -0.     ]
 [ 0.       0.      -0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.00394]]
DirichletB

[06-27 00:21:06][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:21:06][DEBUG] jax_fem: Start timing
[06-27 00:21:06][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:21:06][DEBUG] jax_fem: Function split_and_compute_cell took 0.0664 seconds
[06-27 00:21:06][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:21:06][DEBUG] jax_fem: Before, res l_2 = 975.3260121577068
[06-27 00:21:06][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:21:06][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:21:07][DEBUG] jax_fem: JAX scipy linear solve res = 0.009745564446772671
[06-27 00:21:07][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:21:07][DEBUG] jax_fem: Function split_and_compute_cell took 0.0746 seconds
[06-27 00:21:07][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:21:07][DEBUG] jax_fem: res l_2 = 3.1955688519110006
[06-27 00:21:07][DEBUG] jax_fem:

Simulation: 4.173027276992798
STEP 30 OF 100
COMBINED_CHECKS
(1000,)
16
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]
 [ 0.    0.   -0.03]]
TABLE
COMBINED_CHECKS
(1000,)
17
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.       0.       0.     ]
 [ 0.       0.      -0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.      -0.     ]
 [ 0.       0.      -0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.      -0.     ]
 [ 0.       

[06-27 00:21:20][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:21:20][DEBUG] jax_fem: Start timing
[06-27 00:21:20][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:21:20][DEBUG] jax_fem: Function split_and_compute_cell took 0.0940 seconds
[06-27 00:21:23][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:21:23][DEBUG] jax_fem: Before, res l_2 = 974.7104614386072
[06-27 00:21:23][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:21:23][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:21:27][DEBUG] jax_fem: JAX scipy linear solve res = 0.00961172637786278
[06-27 00:21:27][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:21:27][DEBUG] jax_fem: Function split_and_compute_cell took 0.0824 seconds
[06-27 00:21:27][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:21:27][DEBUG] jax_fem: res l_2 = 2.8929407156308256
[06-27 00:21:27][DEBUG] jax_fem: 

Simulation: 17.57353901863098
STEP 31 OF 100
COMBINED_CHECKS
(1000,)
17
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.00461]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]
 [ 0.       0.      -0.03   ]]
TABLE
COMBINED_CHECKS
(1000,)
18
COMBINED_DISPLACEMENTS
(1000, 3)
[[ 0.       0.       0.     ]
 [ 0.       0.      -0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.       0.     ]
 [ 0.       0.      -0.     ]
 [ 0.       0.      -0.     ]
 [ 0.       0.    

[06-27 00:22:03][DEBUG] jax_fem: Calling the row elimination solver for imposing Dirichlet B.C.
[06-27 00:22:03][DEBUG] jax_fem: Start timing
[06-27 00:22:03][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:22:03][DEBUG] jax_fem: Function split_and_compute_cell took 0.1633 seconds
[06-27 00:22:14][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:22:19][DEBUG] jax_fem: Before, res l_2 = 956.6944040298555
[06-27 00:22:19][DEBUG] jax_fem: Solving linear system with lift solver...
[06-27 00:22:19][DEBUG] jax_fem: Compute and use jacobi preconditioner
[06-27 00:22:24][DEBUG] jax_fem: JAX scipy linear solve res = 0.006361670918550125
[06-27 00:22:24][DEBUG] jax_fem: Computing cell Jacobian and cell residual...
[06-27 00:22:24][DEBUG] jax_fem: Function split_and_compute_cell took 0.1058 seconds
[06-27 00:22:24][DEBUG] jax_fem: Creating sparse matrix with scipy...
[06-27 00:22:24][DEBUG] jax_fem: res l_2 = 2.84494151140441
[06-27 00:22:25][DEBUG] jax_fem: S

Simulation: 112.75409626960754
STEP 32 OF 100



KeyboardInterrupt



In [6]:
testList = [1,2,3]
[-x for x in testList[:2]]

[-1, -2]

In [1]:
from vtk_plotting import create_gif
data_dir = 'data/runs/run_002'
create_gif(data_dir,data_dir)
create_gif(data_dir,data_dir,name="animation2.gif",negative=True)